version: "2"
services:
  client-angular:
    build: .
    ports:
     - "4200:4200"
     - "49153:49153"
     - "9876:9876"
     - "49152:49152"
    volumes:
     - ./:/usr/src/app  
    command: bash